//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabSimulation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        public int CommentID { get; set; }
        public int EducationalLevelID { get; set; }
        public int EducationalYearID { get; set; }
        public int SubjectID { get; set; }
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        [Display(Name = "Comment")]
        [Required(ErrorMessage = "You can't add an empty comment, Please enter your comment if you wish")]
        [RegularExpression(@"^((?!stupid|dog|donkey|caw|animal)[\s\S])*$", ErrorMessage = "Your comment contains inappropriate words")]
        public string Comments { get; set; }
        public Nullable<System.DateTime> CommentDateTime { get; set; } = Convert.ToDateTime(DateTime.Now.ToLongTimeString());

        public virtual User User { get; set; }
        public virtual Experience Experience { get; set; }
    }
}
