//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabSimulation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int EducationalLevelID { get; set; }
        public int EducationalYearID { get; set; }
        public int SubjectID { get; set; }
        public int ExperienceID { get; set; }
        public int UserID { get; set; }
        public int ID { get; set; }
    
        public virtual Experience Experience { get; set; }
        public virtual User User { get; set; }
    }
}
