//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabSimulation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Comments_Users
    {
        public string FullName { get; set; }
        public byte[] Image { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CommentDateTime { get; set; }
        public Nullable<int> UserID { get; set; }
        public int CommentID { get; set; }
        public int ID { get; set; }
        public int SubjectID { get; set; }
        public int EducationalYearID { get; set; }
        public int EducationalLevelID { get; set; }
    }
}
