//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabSimulation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ExperienceInfo
    {
        public string EducationalLevelName { get; set; }
        public string EducationalYearName { get; set; }
        public string SubjectName { get; set; }
        public string ExperienceName { get; set; }
        public string Description { get; set; }
        public Nullable<long> Likes { get; set; }
        public string SrcPath { get; set; }
        public string Image { get; set; }
        public string Type { get; set; }
        public int EducationalLevelID { get; set; }
        public int EducationalYearID { get; set; }
        public int SubjectID { get; set; }
        public int ID { get; set; }
    }
}
